name: analytics-bot
on:
  push:
    paths:
      - .github/workflows/analytics-bot.yml
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - run: echo "Test for analytics-bot"
