name: api-key-hunter
on:
  push:
    paths:
      - .github/workflows/api-key-hunter.yml
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - run: echo "Test for api-key-hunter"
