name: ghpat-test
on:
  push:
    paths:
      - .github/workflows/ghpat-test.yml
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - run: echo "Test for ghpat-test"
