name: master-report
on:
  push:
    paths:
      - .github/workflows/master-report.yml
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - run: echo "Test"
